### ISSUE TITLE
NCCL Timeout/Deadlock when enabling --sync_bn in Distributed Training

### ISSUE THREAD

**Issue by WaningNight** [KaiqiangXiong/CL-MVSNet#14]
Thanks for the great work!

I encountered a DistBackendError (NCCL watchdog timeout) when training with DistributedDataParallel and --sync_bn enabled. The training starts but crashes around Epoch 0 with a collective operation timeout.
With --sync_bn The training hangs and then crashes with Watchdog caught collective operation timeout and without --sync_bn, training works perfectly fine. GPUs are all V100

`(base) zhengyifei24@gcykxjs-Server:~$ CUDA_VISIBLE_DEVICES=1,5 python -m torch.distributed.launch --nproc_per_node=2 --master_port=2345 main.py --sync_bn 
/home/zhengyifei24/miniconda3/bin/python: Error while finding module specification for 'torch.distributed.launch' (ModuleNotFoundError: No module named 'torch')
(base) zhengyifei24@gcykxjs-Server:~$ conda activate ZYF312
(ZYF312) zhengyifei24@gcykxjs-Server:~$ cd /home/zhengyifei24/pyproject/CL-MVSNet/
(ZYF312) zhengyifei24@gcykxjs-Server:~/pyproject/CL-MVSNet$ CUDA_VISIBLE_DEVICES=1,5 python -m torch.distributed.launch --nproc_per_node=2 --master_port=2345 main.py --sync_bn 
/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/distributed/launch.py:207: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
W1213 17:13:55.415000 1497962 site-packages/torch/distributed/run.py:803] 
W1213 17:13:55.415000 1497962 site-packages/torch/distributed/run.py:803] *****************************************
W1213 17:13:55.415000 1497962 site-packages/torch/distributed/run.py:803] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1213 17:13:55.415000 1497962 site-packages/torch/distributed/run.py:803] *****************************************
| distributed init (rank 0): env://
| distributed init (rank 1): env://
dataset train metas: 27097
dataset val metas: 7546
Namespace(num_stage=3, base_channels=8, sample1={'num_hypotheses': 48, 'interval_ratio': 4}, sample2={'num_hypotheses': 32, 'interval_ratio': 2}, sample3={'num_hypotheses': 8, 'interval_ratio': 1}, group=8, img_size=[512, 640], datapath='/home/zhengyifei24/pyproject/CL-MVSNet/dtu_training/', trainlist='datasets/lists/dtu/train.txt', testlist='datasets/lists/dtu/test.txt', dataset_name='dtu_cl', batch_size=1, numdepth=192, interval_scale=1.06, nviews=5, inverse_depth=False, val=False, start_epoch=0, epochs=16, lr=0.0005, wd=0.0, scheduler='steplr', warmup=0.33, milestones=[10, 12, 14], lr_decay=0.5, resume=None, log_dir='./log', dlossw=[0.5, 1.0, 2.0], wrecon=8.0, w_icc=0.01, max_w_icc=0.32, w_scc=0.01, mask_conf=0.95, p_icc=0.1, eval_freq=1, summary_freq=50, test=False, outdir='./outputs', num_worker=4, filter_method='pcd', conf=0.8, thres_view=3, depth_thres=0.001, img_dist_thres=0.75, no_cuda=False, local_rank=0, dist_url='env://', sync_bn=True, rank=0, world_size=2, gpu=0, distributed=True, dist_backend='nccl')
Epoch 0/16:   0% 00/13549 |                                | Elapsed Time: 0:00:00,ETA:  --:--:--,LR: -,Loss: -,Th2: -,Th4: -,Th8: -/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4317.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4317.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/nn/functional.py:5100: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/nn/functional.py:5100: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/optim/lr_scheduler.py:204: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/optim/lr_scheduler.py:204: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
Epoch 0/16:   0% 00/13549 || Elapsed Time: 0:00:44,ETA:  --:--:--,LR: 0.000167,Loss: 26.721|26.721,Th2: 0.970|0.970,Th4: 0.941|0.941,Th8: 0.882|0.882[rank1]:[E1213 17:24:49.042571559 ProcessGroupNCCL.cpp:683] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=716, OpType=ALLREDUCE, NumelIn=128, NumelOut=128, Timeout(ms)=600000) ran for 600049 milliseconds before timing out.
[rank0]:[E1213 17:24:49.071114238 ProcessGroupNCCL.cpp:683] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=716, OpType=ALLREDUCE, NumelIn=1452872, NumelOut=1452872, Timeout(ms)=600000) ran for 600039 milliseconds before timing out.
[rank1]:[E1213 17:24:49.081771127 ProcessGroupNCCL.cpp:2241] [PG ID 0 PG GUID 0(default_pg) Rank 1]  failure detected by watchdog at work sequence id: 716 PG status: last enqueued work: 763, last completed work: 715
[rank1]:[E1213 17:24:49.081831157 ProcessGroupNCCL.cpp:730] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank1]:[E1213 17:24:49.082052958 ProcessGroupNCCL.cpp:2573] [PG ID 0 PG GUID 0(default_pg) Rank 1] First PG on this rank to signal dumping.
[rank0]:[E1213 17:24:49.082111648 ProcessGroupNCCL.cpp:2241] [PG ID 0 PG GUID 0(default_pg) Rank 0]  failure detected by watchdog at work sequence id: 716 PG status: last enqueued work: 747, last completed work: 715
[rank0]:[E1213 17:24:49.082137518 ProcessGroupNCCL.cpp:730] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank0]:[E1213 17:24:49.082246429 ProcessGroupNCCL.cpp:2573] [PG ID 0 PG GUID 0(default_pg) Rank 0] First PG on this rank to signal dumping.
[rank0]:[E1213 17:24:49.328237228 ProcessGroupNCCL.cpp:1858] [PG ID 0 PG GUID 0(default_pg) Rank 0] Received a dump signal due to a collective timeout from this local rank and we will try our best to dump the debug info. Last enqueued NCCL work: 747, last completed NCCL work: 715.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across ranks, the order of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as network errors or bugs in the communications library (e.g. NCCL), etc. 
[rank1]:[E1213 17:24:49.331433657 ProcessGroupNCCL.cpp:1858] [PG ID 0 PG GUID 0(default_pg) Rank 1] Received a dump signal due to a collective timeout from this local rank and we will try our best to dump the debug info. Last enqueued NCCL work: 763, last completed NCCL work: 715.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across ranks, the order of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as network errors or bugs in the communications library (e.g. NCCL), etc. 
[rank1]:[E1213 17:24:49.357766770 ProcessGroupNCCL.cpp:1575] [PG ID 0 PG GUID 0(default_pg) Rank 1] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
[rank0]:[E1213 17:24:49.357795860 ProcessGroupNCCL.cpp:1575] [PG ID 0 PG GUID 0(default_pg) Rank 0] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
[rank0]:[E1213 17:25:50.763620545 ProcessGroupNCCL.cpp:744] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank0]:[E1213 17:25:50.763665695 ProcessGroupNCCL.cpp:758] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[rank0]:[E1213 17:25:50.764687430 ProcessGroupNCCL.cpp:2057] [PG ID 0 PG GUID 0(default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=716, OpType=ALLREDUCE, NumelIn=1452872, NumelOut=1452872, Timeout(ms)=600000) ran for 600039 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:686 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x7425b177cb80 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x247 (0x74255af5a377 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x1691 (0x74255af5ef81 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (0x74255af601cf in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x7425c08dc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x7425c3a94ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x1268c0 (0x7425c3b268c0 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=716, OpType=ALLREDUCE, NumelIn=1452872, NumelOut=1452872, Timeout(ms)=600000) ran for 600039 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:686 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x7425b177cb80 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x247 (0x74255af5a377 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x1691 (0x74255af5ef81 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (0x74255af601cf in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x7425c08dc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x7425c3a94ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x1268c0 (0x7425c3b268c0 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from run at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2063 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x7425b177cb80 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x13364f1 (0x74255af364f1 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xe56b0b (0x74255aa56b0b in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xdc253 (0x7425c08dc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #4: <unknown function> + 0x94ac3 (0x7425c3a94ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #5: <unknown function> + 0x1268c0 (0x7425c3b268c0 in /lib/x86_64-linux-gnu/libc.so.6)

[rank1]:[E1213 17:25:50.849797607 ProcessGroupNCCL.cpp:744] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]:[E1213 17:25:50.849853448 ProcessGroupNCCL.cpp:758] [Rank 1] To avoid data inconsistency, we are taking the entire process down.
[rank1]:[E1213 17:25:50.851195233 ProcessGroupNCCL.cpp:2057] [PG ID 0 PG GUID 0(default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=716, OpType=ALLREDUCE, NumelIn=128, NumelOut=128, Timeout(ms)=600000) ran for 600049 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:686 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x725b6ad7cb80 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x247 (0x725b1455a377 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x1691 (0x725b1455ef81 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (0x725b145601cf in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x725b79edc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x725b7d094ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x1268c0 (0x725b7d1268c0 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 0 PG GUID 0(default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=716, OpType=ALLREDUCE, NumelIn=128, NumelOut=128, Timeout(ms)=600000) ran for 600049 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:686 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x725b6ad7cb80 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x247 (0x725b1455a377 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x1691 (0x725b1455ef81 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (0x725b145601cf in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdc253 (0x725b79edc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x725b7d094ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x1268c0 (0x725b7d1268c0 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from run at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2063 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x725b6ad7cb80 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x13364f1 (0x725b145364f1 in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xe56b0b (0x725b14056b0b in /home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xdc253 (0x725b79edc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #4: <unknown function> + 0x94ac3 (0x725b7d094ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #5: <unknown function> + 0x1268c0 (0x725b7d1268c0 in /lib/x86_64-linux-gnu/libc.so.6)

E1213 17:25:50.704000 1497962 site-packages/torch/distributed/elastic/multiprocessing/api.py:882] failed (exitcode: -6) local_rank: 0 (pid: 1498377) of binary: /home/zhengyifei24/miniconda3/envs/ZYF312/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/distributed/launch.py", line 207, in <module>
    main()
  File "/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/typing_extensions.py", line 3004, in wrapper
    return arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/distributed/launch.py", line 203, in main
    launch(args)
  File "/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/distributed/launch.py", line 188, in launch
    run(args)
  File "/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/distributed/run.py", line 927, in run
    elastic_launch(
  File "/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 156, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhengyifei24/miniconda3/envs/ZYF312/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 293, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
main.py FAILED
--------------------------------------------------------
Failures:
[1]:
  time      : 2025-12-13_17:25:50
  host      : gcykxjs-Server
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 1498378)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 1498378
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-12-13_17:25:50
  host      : gcykxjs-Server
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 1498377)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 1498377
========================================================`

**Comment by KaiqiangXiong** [comment]
I haven’t seen this exact issue, but here are quick triage steps:


Run a single-GPU, single-batch training to confirm the baseline works.
Check data shapes across ranks before sync ops (use DistributedSampler with drop_last=True; fix seeds for consistency).
Try disabling SyncBatchNorm to see if the problem is tied to the SyncBN path.
Verify environment consistency (PyTorch/CUDA/NCCL versions) and consider enabling NCCL logs for more diagnostics.

**Comment by WaningNight** [comment]
Thanks for the quick triage suggestions
Disabling --sync_bn allows the code to run normally, confirming the problem was entirely in the SyncBN path (B=1 caused deadlock, B=2 caused OOM on 31GB cards).
I've already confirmed the baseline is fine (single-GPU run works) and that data consistency is secure (DistributedSampler with drop_last=True).
The main question now is: For CL-MVSNet, how badly will turning off SyncBatchNorm hurt final MVS performance/accuracy?

**Comment by KaiqiangXiong** [comment]
Regarding the impact of turning off SyncBatchNorm on CL-MVSNet's MVS performance/accuracy, I don’t recall the specifics offhand. It might need further testing to confirm.

Also, our experiments were run on 8 V100 GPUs, and other researchers have reproduced the results under the same setup. However, feedback from other issues suggests different GPU configs may yield varying results, though I haven’t verified this myself.
